import type { NextPage } from 'next'
import Head from 'next/head'
import JobsList from '../components/JobsList'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AleannLab Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center pt-[1.8rem] pb-16">
        <JobsList />
      </main>
    </div>
  )
}

export default Home
